// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_GOOGLE_MAPS_API_KEY',
    appId: '1:YOUR_FIREBASE_SENDER_ID:web:595eec569af41cfbc70bb5',
    messagingSenderId: 'YOUR_FIREBASE_SENDER_ID',
    projectId: 'YOUR_GOOGLE_PROJECT_ID',
    authDomain: 'YOUR_GOOGLE_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_GOOGLE_PROJECT_ID.firebasestorage.app',
    measurementId: 'G-W2RL1V76J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_FIREBASE_API_KEY',
    appId: '1:YOUR_SENDER_ID:android:YOUR_ANDROID_APP_ID_1c70bb5',
    messagingSenderId: 'YOUR_FIREBASE_SENDER_ID',
    projectId: 'YOUR_GOOGLE_PROJECT_ID',
    storageBucket: 'YOUR_GOOGLE_PROJECT_ID.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_FIREBASE_API_KEY',
    appId: '1:YOUR_SENDER_ID:ios:YOUR_IOS_APP_ID_1c70bb5',
    messagingSenderId: 'YOUR_FIREBASE_SENDER_ID',
    projectId: 'YOUR_GOOGLE_PROJECT_ID',
    storageBucket: 'YOUR_GOOGLE_PROJECT_ID.firebasestorage.app',
    iosBundleId: 'com.example.rahieeAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_IOS_FIREBASE_API_KEY',
    appId: '1:YOUR_SENDER_ID:ios:YOUR_IOS_APP_ID_1c70bb5',
    messagingSenderId: 'YOUR_FIREBASE_SENDER_ID',
    projectId: 'YOUR_GOOGLE_PROJECT_ID',
    storageBucket: 'YOUR_GOOGLE_PROJECT_ID.firebasestorage.app',
    iosBundleId: 'com.example.rahieeAi',
  );
}
