// ignore_for_file: file_names
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../models/user_model.dart';
import '../models/schedule_model.dart';
import '../services/supabase_service.dart';
import '../utils/app_constant.dart';

class AdminController extends GetxController {
  final SupabaseService _supabaseService = SupabaseService.to;
  late UserModel adminUser;
  
  // Observable variables
  final isLoading = false.obs;
  final isLoadingUsers = false.obs;
  final allUsers = <UserModel>[].obs;
  final selectedUsers = <UserModel>[].obs;
  final selectedDate = DateTime.now().obs;
  final selectedStartTime = TimeOfDay.now().obs;
  final selectedEndTime = TimeOfDay.now().obs;
  final selectedDepartment = 'Restaurant'.obs;
  final userFilterDepartment = 'All'.obs;
  
  // Form variables
  final titleController = TextEditingController();
  final descriptionController = TextEditingController();
  final locationController = TextEditingController();
  final notesController = TextEditingController();
  
  // Department options
  final departments = [
    'Restaurant',
    'Kitchen',
    'Management',
    'Cleaning',
    'Security',
    'Maintenance'
  ].obs;

  @override
  void onInit() {
    super.onInit();
    loadAllUsers();
  }

  @override
  void onClose() {
    titleController.dispose();
    descriptionController.dispose();
    locationController.dispose();
    notesController.dispose();
    super.onClose();
  }

  void initializeWithUser(UserModel user) {
    print('DEBUG: AdminController initializing with user: ${user.fullName}');
    print('DEBUG: User role: ${user.userRole}');
    print('DEBUG: Is admin: ${user.isAdmin}');
    adminUser = user;
  }

  // Load all active users for schedule assignment
  Future<void> loadAllUsers() async {
    try {
      isLoadingUsers.value = true;
      print('DEBUG: Starting to load users from Supabase...');
      
      final usersData = await _supabaseService.select(
        'my_users',
        eq: 'is_active',
        eqValue: true,
        orderBy: 'full_name',
      );
      
      print('DEBUG: Loaded ${usersData.length} documents from Supabase');
      
      allUsers.clear();
      
      for (var userData in usersData) {
        try {
          final user = UserModel.fromMap(userData);
          
          // Only add non-admin users to the schedule assignment list
          if (!user.isAdmin) {
            allUsers.add(user);
            print('DEBUG: Added user: ${user.fullName} (${user.position})');
          }
        } catch (e) {
          print('DEBUG: Error parsing user: $e');
        }
      }
      
      print('DEBUG: Successfully loaded ${allUsers.length} users for scheduling');
      
    } catch (e) {
      print('DEBUG: Error loading users: $e');
      Get.snackbar('Error', 'Failed to load users: $e');
    } finally {
      isLoadingUsers.value = false;
    }
  }

  // Get filtered users based on department filter
  List<UserModel> get filteredUsers {
    if (userFilterDepartment.value == 'All') {
      return allUsers;
    }
    return allUsers.where((user) => user.department == userFilterDepartment.value).toList();
  }

  // Toggle user selection for schedule assignment
  void toggleUserSelection(UserModel user) {
    if (selectedUsers.contains(user)) {
      selectedUsers.remove(user);
    } else {
      selectedUsers.add(user);
    }
    print('DEBUG: Selected users count: ${selectedUsers.length}');
  }

  // Check if user is selected
  bool isUserSelected(UserModel user) {
    return selectedUsers.contains(user);
  }

  // Set selected date
  void setSelectedDate(DateTime date) {
    selectedDate.value = date;
  }

  // Set start time
  void setStartTime(TimeOfDay time) {
    selectedStartTime.value = time;
  }

  // Set end time
  void setEndTime(TimeOfDay time) {
    selectedEndTime.value = time;
  }

  // Set department
  void setDepartment(String department) {
    selectedDepartment.value = department;
  }

  // Create schedule for selected users
  Future<void> createSchedule() async {
    if (!_validateScheduleForm()) return;
    
    try {
      isLoading.value = true;
      
      // Create schedules for each selected user
      for (final user in selectedUsers) {
        final startDateTime = DateTime(
          selectedDate.value.year,
          selectedDate.value.month,
          selectedDate.value.day,
          selectedStartTime.value.hour,
          selectedStartTime.value.minute,
        );
        
        final endDateTime = DateTime(
          selectedDate.value.year,
          selectedDate.value.month,
          selectedDate.value.day,
          selectedEndTime.value.hour,
          selectedEndTime.value.minute,
        );

        final schedule = ScheduleModel(
          scheduleId: '', // Will be generated by Supabase
          title: titleController.text.trim(),
          description: descriptionController.text.trim(),
          startDateTime: startDateTime,
          endDateTime: endDateTime,
          createdByAdminId: adminUser.uId,
          assignedUserId: user.uId,
          department: selectedDepartment.value,
          location: locationController.text.trim(),
          status: 'active',
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
          notes: notesController.text.trim().isEmpty ? null : notesController.text.trim(),
          isActive: true,
        );

        await _supabaseService.insert('employee_schedules', schedule.toMap());
      }
      
      Get.snackbar(
        'Success', 
        'Schedule created for ${selectedUsers.length} employee(s)',
        snackPosition: SnackPosition.TOP,
        backgroundColor: AppConstant.successColor,
        colorText: Colors.white,
      );
      
      _clearForm();
      
    } catch (e) {
      print('DEBUG: Error creating schedule: $e');
      Get.snackbar(
        'Error', 
        'Failed to create schedule: $e',
        snackPosition: SnackPosition.TOP,
        backgroundColor: Colors.red,
        colorText: Colors.white,
      );
    } finally {
      isLoading.value = false;
    }
  }

  // Validate schedule form
  bool _validateScheduleForm() {
    if (titleController.text.trim().isEmpty) {
      Get.snackbar('Validation Error', 'Please enter a schedule title');
      return false;
    }
    
    if (selectedUsers.isEmpty) {
      Get.snackbar('Validation Error', 'Please select at least one employee');
      return false;
    }
    
    if (locationController.text.trim().isEmpty) {
      Get.snackbar('Validation Error', 'Please enter a location');
      return false;
    }
    
    // Check if end time is after start time
    final startMinutes = selectedStartTime.value.hour * 60 + selectedStartTime.value.minute;
    final endMinutes = selectedEndTime.value.hour * 60 + selectedEndTime.value.minute;
    
    if (endMinutes <= startMinutes) {
      Get.snackbar('Validation Error', 'End time must be after start time');
      return false;
    }
    
    return true;
  }

  // Clear form after successful creation
  void _clearForm() {
    titleController.clear();
    descriptionController.clear();
    locationController.clear();
    notesController.clear();
    selectedUsers.clear();
    selectedDate.value = DateTime.now();
    selectedStartTime.value = TimeOfDay.now();
    selectedEndTime.value = TimeOfDay.now();
    selectedDepartment.value = 'Restaurant';
  }

  // Get users by department
  List<UserModel> getUsersByDepartment(String department) {
    return allUsers.where((user) => user.department == department).toList();
  }

  // Get unique departments from users
  List<String> getUniqueDepartments() {
    final deps = allUsers.map((user) => user.department).toSet().toList();
    deps.sort();
    return ['All', ...deps];
  }

  // Get user count by department
  int getUserCountByDepartment(String department) {
    if (department == 'All') return allUsers.length;
    return allUsers.where((user) => user.department == department).length;
  }
}
